version: '2.2'

services:
    reverse:
        build: ./
        image: fea
        volumes: 
            - ./share:/home/pwn:ro
            - ./xinetd:/etc/xinetd.d/xinetd:ro
            - ./tmp:/tmp:rw
        ports:
            - "30212:8888"
        expose:
            - "8888"
        pids_limit: 1024
        cpus: 1
        restart: unless-stopped
        
#networks:
#    default:
#        external:
#            name: pwn

